// Generated by scripts/images.mjs from assets/images; do not edit by hand. Each entry carries the
// explicit dimensions of the AVIF/WebP pair under public/images (CLS budget 0).
import type { SiteImage } from '@/content/schema';

export const images = {
  'cover': { src: '/images/cover', width: 1920, height: 600, alt: '', widths: [640, 1280] },
  'avatar': { src: '/images/avatar', width: 320, height: 320, alt: 'Jason Robitaille' },
  'enact-cli': { src: '/images/enact-cli', width: 1200, height: 750, alt: 'Enact framework site' },
  'svl-simulator': {
    src: '/images/svl-simulator',
    width: 1200,
    height: 750,
    alt: 'SVL Simulator web platform'
  },
  'retailverse-web': {
    src: '/images/retailverse-web',
    width: 1200,
    height: 750,
    alt: 'RetailVerse Web 3D viewer showing an LG washer'
  },
  'webos-homebrew': {
    src: '/images/webos-homebrew',
    width: 1200,
    height: 750,
    alt: 'WebOS Quick Install desktop application'
  },
  'gamelist-utils-muos': {
    src: '/images/gamelist-utils-muos',
    width: 1200,
    height: 750,
    alt: 'Terminal showing gamelist-utils --help output'
  },
  'not-found': { src: '/images/not-found', width: 1920, height: 600, alt: '', widths: [640, 1280] },
  'ufo-and-cow': {
    src: '/images/ufo-and-cow.svg',
    width: 420,
    height: 420,
    alt: 'A UFO beaming up a cow'
  }
} as const satisfies Record<string, SiteImage>;
